export enum ActivityStage {
  DESIGN_REVIEW = 'DESIGN_REVIEW',
  QUOTATION = 'QUOTATION',
  CUTTING = 'CUTTING',
  PRODUCTION = 'PRODUCTION',
  INSTALLATION = 'INSTALLATION',
  DELIVERY = 'DELIVERY',
  CLOSURE = 'CLOSURE',
  CUSTOM = 'CUSTOM'
}
