export enum AlertType {
  DUE_SOON = 'DUE_SOON',
  OVERDUE = 'OVERDUE',
  BLOCKED_ACTIVITY = 'BLOCKED_ACTIVITY',
  INCIDENT = 'INCIDENT',
  QUOTE_OUTDATED = 'QUOTE_OUTDATED',
  CUTTING_LIST_OUTDATED = 'CUTTING_LIST_OUTDATED',
  CUSTOM = 'CUSTOM'
}
